MODULE CI_SUBR 
    INTERFACE 
!       SUBROUTINE  GetCIJKL1body_Par(MYID,VIN) 
!        ! CALL  GetCIJKL1body_Par(MYID,VIN) 
!          COMPLEX*16 ::  VIN(:) 
!          INTEGER    :: MYID 
!       END SUBROUTINE  GetCIJKL1body_Par 
!       SUBROUTINE  GetCIJKL2body_Par(MYID,VIN) 
!           ! CALL  GetCIJKL2body_Par(MYID,VIN) 
!          COMPLEX*16 ::  VIN(:) 
!          INTEGER    :: MYID 
!       END SUBROUTINE  GetCIJKL2body_Par 
    SUBROUTINE  PrdCIJKL1body_M_OMP(MYID,VIN)
       COMPLEX*16 ::  VIN(:)
       INTEGER    :: MYID
    END SUBROUTINE  PrdCIJKL1body_M_OMP
    SUBROUTINE  PrdCIJKL2body_M_OMP(MYID,VIN)
       COMPLEX*16 ::  VIN(:)
       INTEGER    :: MYID
    END SUBROUTINE  PrdCIJKL2body_M_OMP
    SUBROUTINE  GetCIJKL1body_1(MYID,VIN)
       COMPLEX*16 ::  VIN(:)
       INTEGER    :: MYID
    END SUBROUTINE  GetCIJKL1body_1
    SUBROUTINE  GetCIJKL2body_1(MYID,VIN)
       COMPLEX*16 ::  VIN(:)
       INTEGER    :: MYID
    END SUBROUTINE  GetCIJKL2body_1
    SUBROUTINE  GetCIJKL1body_2_OMP(MYID,VIN)
       COMPLEX*16 ::  VIN(:)
       INTEGER    :: MYID
    END SUBROUTINE  GetCIJKL1body_2_OMP
    SUBROUTINE  GetCIJKL2body_2_OMP(MYID,VIN)
       COMPLEX*16 ::  VIN(:)
       INTEGER    :: MYID
    END SUBROUTINE  GetCIJKL2body_2_OMP
    SUBROUTINE  GetCIJKL1body_3_OMP(MYID,VIN)
       COMPLEX*16 ::  VIN(:)
       INTEGER    :: MYID
    END SUBROUTINE  GetCIJKL1body_3_OMP
    SUBROUTINE  GetCIJKL2body_3_OMP(MYID,VIN)
       COMPLEX*16 ::  VIN(:)
       INTEGER    :: MYID
    END SUBROUTINE  GetCIJKL2body_3_OMP
    SUBROUTINE  GetCIJKL1body_4_OMP(MYID,VIN)
       COMPLEX*16 ::  VIN(:)
       INTEGER    :: MYID
    END SUBROUTINE  GetCIJKL1body_4_OMP
    SUBROUTINE  GetCIJKL2body_4_OMP(MYID,VIN)
       COMPLEX*16 ::  VIN(:)
       INTEGER    :: MYID
    END SUBROUTINE  GetCIJKL2body_4_OMP
    SUBROUTINE  GetCIJKL1body_5_OMP(MYID,VIN)
       COMPLEX*16 ::  VIN(:)
       INTEGER    :: MYID
    END SUBROUTINE  GetCIJKL1body_5_OMP
    SUBROUTINE  GetCIJKL2body_5_OMP(MYID,VIN)
       COMPLEX*16 ::  VIN(:)
       INTEGER    :: MYID
    END SUBROUTINE  GetCIJKL2body_5_OMP
    SUBROUTINE  GetCIJKL1body_6_OMP(MYID,VIN)
       COMPLEX*16 ::  VIN(:)
       INTEGER    :: MYID
    END SUBROUTINE  GetCIJKL1body_6_OMP
    SUBROUTINE  GetCIJKL2body_6_OMP(MYID,VIN)
       COMPLEX*16 ::  VIN(:)
       INTEGER    :: MYID
    END SUBROUTINE  GetCIJKL2body_6_OMP
    SUBROUTINE  GetCIJKL1body_7_OMP(MYID,VIN)
       COMPLEX*16 ::  VIN(:)
       INTEGER    :: MYID
    END SUBROUTINE  GetCIJKL1body_7_OMP
    SUBROUTINE  GetCIJKL2body_7_OMP(MYID,VIN)
       COMPLEX*16 ::  VIN(:)
       INTEGER    :: MYID
    END SUBROUTINE  GetCIJKL2body_7_OMP
    SUBROUTINE  GetCIJKL1body_8_OMP(MYID,VIN)
       COMPLEX*16 ::  VIN(:)
       INTEGER    :: MYID
    END SUBROUTINE  GetCIJKL1body_8_OMP
    SUBROUTINE  GetCIJKL2body_8_OMP(MYID,VIN)
       COMPLEX*16 ::  VIN(:)
       INTEGER    :: MYID
    END SUBROUTINE  GetCIJKL2body_8_OMP
    SUBROUTINE  GetCIJKL1body_9_OMP(MYID,VIN)
       COMPLEX*16 ::  VIN(:)
       INTEGER    :: MYID
    END SUBROUTINE  GetCIJKL1body_9_OMP
    SUBROUTINE  GetCIJKL2body_9_OMP(MYID,VIN)
       COMPLEX*16 ::  VIN(:)
       INTEGER    :: MYID
    END SUBROUTINE  GetCIJKL2body_9_OMP
    SUBROUTINE  GetCIJKL1body_10_OMP(MYID,VIN)
       COMPLEX*16 ::  VIN(:)
       INTEGER    :: MYID
    END SUBROUTINE  GetCIJKL1body_10_OMP
    SUBROUTINE  GetCIJKL2body_10_OMP(MYID,VIN)
       COMPLEX*16 ::  VIN(:)
       INTEGER    :: MYID
    END SUBROUTINE  GetCIJKL2body_10_OMP
    SUBROUTINE  GetCIJKL1body_11_OMP(MYID,VIN)
       COMPLEX*16 ::  VIN(:)
       INTEGER    :: MYID
    END SUBROUTINE  GetCIJKL1body_11_OMP
    SUBROUTINE  GetCIJKL2body_11_OMP(MYID,VIN)
       COMPLEX*16 ::  VIN(:)
       INTEGER    :: MYID
    END SUBROUTINE  GetCIJKL2body_11_OMP
    SUBROUTINE  GetCIJKL1body_12_OMP(MYID,VIN)
       COMPLEX*16 ::  VIN(:)
       INTEGER    :: MYID
    END SUBROUTINE  GetCIJKL1body_12_OMP
    SUBROUTINE  GetCIJKL2body_12_OMP(MYID,VIN)
       COMPLEX*16 ::  VIN(:)
       INTEGER    :: MYID
    END SUBROUTINE  GetCIJKL2body_12_OMP
    SUBROUTINE  GetCIJKL1body_13_OMP(MYID,VIN)
       COMPLEX*16 ::  VIN(:)
       INTEGER    :: MYID
    END SUBROUTINE  GetCIJKL1body_13_OMP
    SUBROUTINE  GetCIJKL2body_13_OMP(MYID,VIN)
       COMPLEX*16 ::  VIN(:)
       INTEGER    :: MYID
    END SUBROUTINE  GetCIJKL2body_13_OMP
    SUBROUTINE  GetCIJKL1body_14_OMP(MYID,VIN)
       COMPLEX*16 ::  VIN(:)
       INTEGER    :: MYID
    END SUBROUTINE  GetCIJKL1body_14_OMP
    SUBROUTINE  GetCIJKL2body_14_OMP(MYID,VIN)
       COMPLEX*16 ::  VIN(:)
       INTEGER    :: MYID
    END SUBROUTINE  GetCIJKL2body_14_OMP
    SUBROUTINE  GetCIJKL1body_15_OMP(MYID,VIN)
       COMPLEX*16 ::  VIN(:)
       INTEGER    :: MYID
    END SUBROUTINE  GetCIJKL1body_15_OMP
    SUBROUTINE  GetCIJKL2body_15_OMP(MYID,VIN)
       COMPLEX*16 ::  VIN(:)
       INTEGER    :: MYID
    END SUBROUTINE  GetCIJKL2body_15_OMP
    SUBROUTINE  GetCIJKL1body_16_OMP(MYID,VIN)
       COMPLEX*16 ::  VIN(:)
       INTEGER    :: MYID
    END SUBROUTINE  GetCIJKL1body_16_OMP
    SUBROUTINE  GetCIJKL2body_16_OMP(MYID,VIN)
       COMPLEX*16 ::  VIN(:)
       INTEGER    :: MYID
    END SUBROUTINE  GetCIJKL2body_16_OMP
    SUBROUTINE  GetCIJKL1body_17_OMP(MYID,VIN)
       COMPLEX*16 ::  VIN(:)
       INTEGER    :: MYID
    END SUBROUTINE  GetCIJKL1body_17_OMP
    SUBROUTINE  GetCIJKL2body_17_OMP(MYID,VIN)
       COMPLEX*16 ::  VIN(:)
       INTEGER    :: MYID
    END SUBROUTINE  GetCIJKL2body_17_OMP
    SUBROUTINE  GetCIJKL1body_18_OMP(MYID,VIN)
       COMPLEX*16 ::  VIN(:)
       INTEGER    :: MYID
    END SUBROUTINE  GetCIJKL1body_18_OMP
    SUBROUTINE  GetCIJKL2body_18_OMP(MYID,VIN)
       COMPLEX*16 ::  VIN(:)
       INTEGER    :: MYID
    END SUBROUTINE  GetCIJKL2body_18_OMP
    SUBROUTINE  GetCIJKL1body_19_OMP(MYID,VIN)
       COMPLEX*16 ::  VIN(:)
       INTEGER    :: MYID
    END SUBROUTINE  GetCIJKL1body_19_OMP
    SUBROUTINE  GetCIJKL2body_19_OMP(MYID,VIN)
       COMPLEX*16 ::  VIN(:)
       INTEGER    :: MYID
    END SUBROUTINE  GetCIJKL2body_19_OMP
    SUBROUTINE  GetCIJKL1body_20_OMP(MYID,VIN)
       COMPLEX*16 ::  VIN(:)
       INTEGER    :: MYID
    END SUBROUTINE  GetCIJKL1body_20_OMP
    SUBROUTINE  GetCIJKL2body_20_OMP(MYID,VIN)
       COMPLEX*16 ::  VIN(:)
       INTEGER    :: MYID
    END SUBROUTINE  GetCIJKL2body_20_OMP
    SUBROUTINE  GetCIJKL1body_21_OMP(MYID,VIN)
       COMPLEX*16 ::  VIN(:)
       INTEGER    :: MYID
    END SUBROUTINE  GetCIJKL1body_21_OMP
    SUBROUTINE  GetCIJKL2body_21_OMP(MYID,VIN)
       COMPLEX*16 ::  VIN(:)
       INTEGER    :: MYID
    END SUBROUTINE  GetCIJKL2body_21_OMP
    SUBROUTINE  GetCIJKL1body_22_OMP(MYID,VIN)
       COMPLEX*16 ::  VIN(:)
       INTEGER    :: MYID
    END SUBROUTINE  GetCIJKL1body_22_OMP
    SUBROUTINE  GetCIJKL2body_22_OMP(MYID,VIN)
       COMPLEX*16 ::  VIN(:)
       INTEGER    :: MYID
    END SUBROUTINE  GetCIJKL2body_22_OMP
    SUBROUTINE  GetCIJKL1body_23_OMP(MYID,VIN)
       COMPLEX*16 ::  VIN(:)
       INTEGER    :: MYID
    END SUBROUTINE  GetCIJKL1body_23_OMP
    SUBROUTINE  GetCIJKL2body_23_OMP(MYID,VIN)
       COMPLEX*16 ::  VIN(:)
       INTEGER    :: MYID
    END SUBROUTINE  GetCIJKL2body_23_OMP
    SUBROUTINE  GetCIJKL1body_24_OMP(MYID,VIN)
       COMPLEX*16 ::  VIN(:)
       INTEGER    :: MYID
    END SUBROUTINE  GetCIJKL1body_24_OMP
    SUBROUTINE  GetCIJKL2body_24_OMP(MYID,VIN)
       COMPLEX*16 ::  VIN(:)
       INTEGER    :: MYID
    END SUBROUTINE  GetCIJKL2body_24_OMP
    SUBROUTINE  GetCIJKL1body_25_OMP(MYID,VIN)
       COMPLEX*16 ::  VIN(:)
       INTEGER    :: MYID
    END SUBROUTINE  GetCIJKL1body_25_OMP
    SUBROUTINE  GetCIJKL2body_25_OMP(MYID,VIN)
       COMPLEX*16 ::  VIN(:)
       INTEGER    :: MYID
    END SUBROUTINE  GetCIJKL2body_25_OMP
    SUBROUTINE  GetCIJKL1body_26_OMP(MYID,VIN)
       COMPLEX*16 ::  VIN(:)
       INTEGER    :: MYID
    END SUBROUTINE  GetCIJKL1body_26_OMP
    SUBROUTINE  GetCIJKL2body_26_OMP(MYID,VIN)
       COMPLEX*16 ::  VIN(:)
       INTEGER    :: MYID
    END SUBROUTINE  GetCIJKL2body_26_OMP
    SUBROUTINE  GetCIJKL1body_27_OMP(MYID,VIN)
       COMPLEX*16 ::  VIN(:)
       INTEGER    :: MYID
    END SUBROUTINE  GetCIJKL1body_27_OMP
    SUBROUTINE  GetCIJKL2body_27_OMP(MYID,VIN)
       COMPLEX*16 ::  VIN(:)
       INTEGER    :: MYID
    END SUBROUTINE  GetCIJKL2body_27_OMP
    SUBROUTINE  GetCIJKL1body_28_OMP(MYID,VIN)
       COMPLEX*16 ::  VIN(:)
       INTEGER    :: MYID
    END SUBROUTINE  GetCIJKL1body_28_OMP
    SUBROUTINE  GetCIJKL2body_28_OMP(MYID,VIN)
       COMPLEX*16 ::  VIN(:)
       INTEGER    :: MYID
    END SUBROUTINE  GetCIJKL2body_28_OMP
    SUBROUTINE  GetCIJKL1body_29_OMP(MYID,VIN)
       COMPLEX*16 ::  VIN(:)
       INTEGER    :: MYID
    END SUBROUTINE  GetCIJKL1body_29_OMP
    SUBROUTINE  GetCIJKL2body_29_OMP(MYID,VIN)
       COMPLEX*16 ::  VIN(:)
       INTEGER    :: MYID
    END SUBROUTINE  GetCIJKL2body_29_OMP
    SUBROUTINE  GetCIJKL1body_30_OMP(MYID,VIN)
       COMPLEX*16 ::  VIN(:)
       INTEGER    :: MYID
    END SUBROUTINE  GetCIJKL1body_30_OMP
    SUBROUTINE  GetCIJKL2body_30_OMP(MYID,VIN)
       COMPLEX*16 ::  VIN(:)
       INTEGER    :: MYID
    END SUBROUTINE  GetCIJKL2body_30_OMP
    END INTERFACE
END MODULE CI_SUBR
